version: '3.7'

services:
  user_service:
    build: .
    command: python user_service.py
    ports:
      - "5001:5001"
    depends_on:
      - db

  plant_service:
    build: .
    command: python plant_service.py
    ports:
      - "5002:5002"
    depends_on:
      - db

  simulation_service:
    build: .
    command: python simulation_service.py
    ports:
      - "5003:5003"
    depends_on:
      - db
      - plant_service

  websocket_service:
    build: .
    command: python websocket_service.py
    ports:
      - "5004:5004"
  
  bug_service:
    build: .
    command: python bug_service.py
    ports:
      - "5010:5010"
    depends_on:
      - db

  main_app:
    build: .
    command: python main_app.py
    ports:
      - "5005:5000"
    depends_on:
      - user_service
      - plant_service
      - simulation_service
      - websocket_service

  db:
    image: postgres:12
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
